name: Package Binaries
description: "Collect release binaries + docs into a tar.gz/zip."
inputs:
  pack:   { required: true, description: "Package name e.g. repository-name" }
  tag:    { required: true, description: "Tag e.g. v.1.2.3" }
  label:  { required: true, description: "Environment label e.g. linux-x86_64" }
  target: { required: true, description: "Target of cargo build, e.g. x86_64-unknown-linux-gnu" }

runs:
  using: "composite"
  steps:
    - if: runner.os != 'Windows'
      shell: bash
      run: |
        . "${{ github.action_path }}/package.sh" \
          "${{ inputs.pack }}" \
          "${{ inputs.tag }}" \
          "${{ inputs.label }}" \
          "${{ inputs.target }}"
    - if: runner.os == 'Windows'
      shell: pwsh
      run: |
        & "${{ github.action_path }}/package.ps1" `
          "${{ inputs.pack }}" `
          "${{ inputs.tag }}" `
          "${{ inputs.label }}" `
          "${{ inputs.target }}"
